// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgi7UPNDwAYIL6UgGZ10xQR4yqhXDADBY',
    appId: '1:413705168066:web:aaa6ddc7077221e853075b',
    messagingSenderId: '413705168066',
    projectId: 'sgela-ai-33',
    authDomain: 'sgela-ai-33.firebaseapp.com',
    storageBucket: 'sgela-ai-33.appspot.com',
    measurementId: 'G-YXD66KLEQ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjVYccOuUD9ucbwbkYTRHDHymoVTNBQsw',
    appId: '1:413705168066:android:1e1d6b669d8d14dd53075b',
    messagingSenderId: '413705168066',
    projectId: 'sgela-ai-33',
    storageBucket: 'sgela-ai-33.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZx8B3sOgilvxvOwtjfi3Zy0HiU3SikvM',
    appId: '1:413705168066:ios:9887590b7668875253075b',
    messagingSenderId: '413705168066',
    projectId: 'sgela-ai-33',
    storageBucket: 'sgela-ai-33.appspot.com',
    androidClientId: '413705168066-hjrnikl476fb9baei10k36c523p81vih.apps.googleusercontent.com',
    iosClientId: '413705168066-u92lr8lb14so9m38knq6lhno0i70a6dr.apps.googleusercontent.com',
    iosBundleId: 'com.boha.sgelaSponsorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZx8B3sOgilvxvOwtjfi3Zy0HiU3SikvM',
    appId: '1:413705168066:ios:d3b2b217d5a0f42553075b',
    messagingSenderId: '413705168066',
    projectId: 'sgela-ai-33',
    storageBucket: 'sgela-ai-33.appspot.com',
    androidClientId: '413705168066-hjrnikl476fb9baei10k36c523p81vih.apps.googleusercontent.com',
    iosClientId: '413705168066-cj2flr1tjuucdovn6bgnuvj01kitp5s6.apps.googleusercontent.com',
    iosBundleId: 'com.boha.sgelaSponsorApp.RunnerTests',
  );
}
